/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const CategoryDto = z.object({
  id: z.string(),
  type: z.string(),
  title: z.string(),
  description: z.string(),
  icon: z.string(),
})

export type CategoryDto = z.infer<typeof CategoryDto>