/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { IngredientRequest } from './IngredientRequest'
import { z } from 'zod/v4'

export const CreateRecipeRequest = z.object({
  title: z.string(),
  headline: z.string(),
  preparationTime: z.int().optional(),
  cookTime: z.int().optional(),
  mealTypeId: z.string(),
  categoryIds: z.array(z.string()),
  instructions: z.array(z.string()),
  get ingredients() {
    return z.array(IngredientRequest)
  },
})

export type CreateRecipeRequest = z.infer<typeof CreateRecipeRequest>