/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const Feedback = z.object({
  id: z.int().optional(),
  createdAt: z.iso.datetime({ local: true }),
  commenter: z.string(),
  rating: z.int(),
  comment: z.string(),
})

export type Feedback = z.infer<typeof Feedback>