/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { MeDto } from './MeDto'
import { z } from 'zod/v4'

/**
 * @description OK
 */
export const GetMe200 = MeDto

export type GetMe200 = z.infer<typeof GetMe200>

export const GetMeQueryResponse = GetMe200

export type GetMeQueryResponse = z.infer<typeof GetMeQueryResponse>