/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { DetailedRecipeDto } from './DetailedRecipeDto'
import { z } from 'zod/v4'

export const GetRecipeResponse = z.object({
  get recipe() {
    return DetailedRecipeDto
  },
})

export type GetRecipeResponse = z.infer<typeof GetRecipeResponse>