/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { Ingredient } from './Ingredient'
import { z } from 'zod/v4'

export const GetRecipeIngredientsResponse = z.object({
  id: z.string(),
  get ingredients() {
    return z.array(Ingredient)
  },
})

export type GetRecipeIngredientsResponse = z.infer<typeof GetRecipeIngredientsResponse>