/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { Feedback } from './Feedback'
import { z } from 'zod/v4'

export const GetRecipeFeedbacksResponse = z.object({
  get feedbacks() {
    return z.array(Feedback)
  },
})

export type GetRecipeFeedbacksResponse = z.infer<typeof GetRecipeFeedbacksResponse>