/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { RecipeDto } from './RecipeDto'
import { z } from 'zod/v4'

export const GetSearchDetailResponse = z.object({
  get recipe() {
    return RecipeDto
  },
})

export type GetSearchDetailResponse = z.infer<typeof GetSearchDetailResponse>