/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const ImageDto = z.object({
  id: z.string(),
  src: z.string(),
  title: z.string(),
})

export type ImageDto = z.infer<typeof ImageDto>