/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const IncrementLikesResponse = z.object({
  recipeId: z.string(),
  newLikes: z.int(),
})

export type IncrementLikesResponse = z.infer<typeof IncrementLikesResponse>