/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const Ingredient = z.object({
  name: z.string(),
  amount: z.number(),
  unit: z.string(),
  orderNo: z.int(),
})

export type Ingredient = z.infer<typeof Ingredient>