/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const NewFeedback = z.object({
  commenter: z.string().min(3).max(2147483647),
  stars: z.int().min(0).max(5),
  comment: z.string(),
})

export type NewFeedback = z.infer<typeof NewFeedback>