/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { CreateRecipeMutationRequest, CreateRecipe200, CreateRecipeMutationResponse } from './CreateRecipe'
import { GetCategories200, GetCategoriesQueryResponse } from './GetCategories'
import { GetMealTypes200, GetMealTypesQueryResponse } from './GetMealTypes'

export const operations = {
  createRecipe: {
    request: CreateRecipeMutationRequest,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: CreateRecipe200,
      default: CreateRecipeMutationResponse,
    },
    errors: {},
  },
  getMealTypes: {
    request: undefined,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: GetMealTypes200,
      default: GetMealTypesQueryResponse,
    },
    errors: {},
  },
  getCategories: {
    request: undefined,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: GetCategories200,
      default: GetCategoriesQueryResponse,
    },
    errors: {},
  },
} as const

export const paths = {
  '/api/admin/recipe': {
    post: operations['createRecipe'],
  },
  '/api/admin/meal-types': {
    get: operations['getMealTypes'],
  },
  '/api/admin/categories': {
    get: operations['getCategories'],
  },
} as const