/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { CreateRecipeMutationRequest, CreateRecipe200, CreateRecipeMutationResponse } from './CreateRecipe'
import { GetCategories200, GetCategoriesQueryResponse } from './GetCategories'
import { GetImages200, GetImagesQueryResponse } from './GetImages'
import { GetMe200, GetMeQueryResponse } from './GetMe'
import { GetMealTypes200, GetMealTypesQueryResponse } from './GetMealTypes'
import { UploadImageMutationRequest, UploadImage200, UploadImageMutationResponse } from './UploadImage'

export const operations = {
  createRecipe: {
    request: CreateRecipeMutationRequest,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: CreateRecipe200,
      default: CreateRecipeMutationResponse,
    },
    errors: {},
  },
  getImages: {
    request: undefined,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: GetImages200,
      default: GetImagesQueryResponse,
    },
    errors: {},
  },
  uploadImage: {
    request: UploadImageMutationRequest,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: UploadImage200,
      default: UploadImageMutationResponse,
    },
    errors: {},
  },
  getMealTypes: {
    request: undefined,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: GetMealTypes200,
      default: GetMealTypesQueryResponse,
    },
    errors: {},
  },
  getMe: {
    request: undefined,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: GetMe200,
      default: GetMeQueryResponse,
    },
    errors: {},
  },
  getCategories: {
    request: undefined,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: GetCategories200,
      default: GetCategoriesQueryResponse,
    },
    errors: {},
  },
} as const

export const paths = {
  '/api/admin/recipe': {
    post: operations['createRecipe'],
  },
  '/api/admin/images': {
    get: operations['getImages'],
    post: operations['uploadImage'],
  },
  '/api/admin/meal-types': {
    get: operations['getMealTypes'],
  },
  '/api/admin/me': {
    get: operations['getMe'],
  },
  '/api/admin/categories': {
    get: operations['getCategories'],
  },
} as const