/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { RecipeDto } from './RecipeDto'
import { z } from 'zod/v4'

export const PageResponseRecipeDto = z.object({
  get content() {
    return z.array(RecipeDto)
  },
  pageNumber: z.int(),
  totalPages: z.int(),
  hasNext: z.boolean(),
  hasPrevious: z.boolean(),
  meta: z.string().optional(),
})

export type PageResponseRecipeDto = z.infer<typeof PageResponseRecipeDto>