/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { RecipeSummaryDto } from './RecipeSummaryDto'
import { z } from 'zod/v4'

export const PageResponseRecipeSummaryDto = z.object({
  get content() {
    return z.array(RecipeSummaryDto)
  },
  pageNumber: z.int(),
  totalPages: z.int(),
  hasNext: z.boolean(),
  hasPrevious: z.boolean(),
  meta: z.string().optional(),
})

export type PageResponseRecipeSummaryDto = z.infer<typeof PageResponseRecipeSummaryDto>