/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { Feedback } from './Feedback'
import { z } from 'zod/v4'

export const PageResponseFeedback = z.object({
  get content() {
    return z.array(Feedback)
  },
  pageNumber: z.int(),
  totalPages: z.int(),
  hasNext: z.boolean(),
  hasPrevious: z.boolean(),
  meta: z.string().optional(),
})

export type PageResponseFeedback = z.infer<typeof PageResponseFeedback>