/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { Feedback } from './Feedback'
import { z } from 'zod/v4'

export const PostFeedbackResponse = z.object({
  get newFeedback() {
    return Feedback
  },
})

export type PostFeedbackResponse = z.infer<typeof PostFeedbackResponse>