/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { NewFeedback } from './NewFeedback'
import { z } from 'zod/v4'

export const PostFeedbackRequest = z.object({
  get feedbackData() {
    return NewFeedback
  },
})

export type PostFeedbackRequest = z.infer<typeof PostFeedbackRequest>