/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const PostNewsletterRegistrationRequest = z.object({
  email: z.string(),
})

export type PostNewsletterRegistrationRequest = z.infer<typeof PostNewsletterRegistrationRequest>