/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const PostNewsletterRegistrationResponse = z.object({
  email: z.string(),
})

export type PostNewsletterRegistrationResponse = z.infer<typeof PostNewsletterRegistrationResponse>