/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const RecipeSummaryDto = z.object({
  id: z.string(),
  title: z.string(),
  mealType: z.string(),
})

export type RecipeSummaryDto = z.infer<typeof RecipeSummaryDto>