/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { ImageDto } from './ImageDto'
import { z } from 'zod/v4'

/**
 * @description OK
 */
export const UploadImage200 = ImageDto

export type UploadImage200 = z.infer<typeof UploadImage200>

export const UploadImageMutationRequest = z.object({
  file: z.instanceof(File).describe('Imagefile'),
  title: z.string().describe('Title (used for alt attribute)'),
})

export type UploadImageMutationRequest = z.infer<typeof UploadImageMutationRequest>

export const UploadImageMutationResponse = UploadImage200

export type UploadImageMutationResponse = z.infer<typeof UploadImageMutationResponse>