/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

import { ImageDto } from './ImageDto'
import { IngredientDto } from './IngredientDto'
import { InstructionDto } from './InstructionDto'

export const AdminRecipeDto = z.object({
  categoryIds: z.array(z.string()),
  cookTime: z.int().optional(),
  createdAt: z.iso.datetime({ local: true }),
  feedbackCount: z.int(),
  headline: z.string(),
  id: z.string(),
  get image() {
    return ImageDto
  },
  get ingredients() {
    return z.array(IngredientDto)
  },
  get instructions() {
    return z.array(InstructionDto)
  },
  likes: z.int(),
  mealTypeId: z.string(),
  preparationTime: z.int().optional(),
  title: z.string(),
  updatedAt: z.iso.datetime({ local: true }),
})

export type AdminRecipeDto = z.infer<typeof AdminRecipeDto>