/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { ApprovalStatus } from './ApprovalStatus'
import { z } from 'zod/v4'

export const AdminFeedbackDto = z.object({
  get approvalStatus() {
    return ApprovalStatus
  },
  comment: z.string(),
  commenter: z.string(),
  createdAt: z.iso.datetime({ local: true }),
  id: z.string(),
  rating: z.int(),
  recipeId: z.string(),
  recipeTitle: z.string(),
  updatedAt: z.iso.datetime({ local: true }),
})

export type AdminFeedbackDto = z.infer<typeof AdminFeedbackDto>