/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { ImageDto } from './ImageDto'
import { IngredientDto } from './IngredientDto'
import { InstructionDto } from './InstructionDto'
import { z } from 'zod/v4'

export const AdminRecipeDto = z.object({
  approvedFeedbackCount: z.int(),
  categoryIds: z.array(z.string()),
  cookTime: z.int().optional(),
  createdAt: z.iso.datetime({ local: true }),
  headline: z.string(),
  id: z.string(),
  get image() {
    return ImageDto
  },
  get ingredients() {
    return z.array(IngredientDto)
  },
  get instructions() {
    return z.array(InstructionDto)
  },
  likes: z.int(),
  mealTypeId: z.string(),
  pendingFeedbackCount: z.int(),
  preparationTime: z.int().optional(),
  rejectedFeedbackCount: z.int(),
  title: z.string(),
  updatedAt: z.iso.datetime({ local: true }),
})

export type AdminRecipeDto = z.infer<typeof AdminRecipeDto>