/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const ApprovalStatus = z.enum(['APPROVAL_PENDING', 'APPROVED', 'REJECTED'])

export type ApprovalStatus = z.infer<typeof ApprovalStatus>