/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

import { CreateRecipeRequest } from './CreateRecipeRequest'
import { DetailedRecipeDto } from './DetailedRecipeDto'

/**
 * @description OK
 */
export const CreateRecipe200 = DetailedRecipeDto

export type CreateRecipe200 = z.infer<typeof CreateRecipe200>

export const CreateRecipeMutationRequest = CreateRecipeRequest

export type CreateRecipeMutationRequest = z.infer<typeof CreateRecipeMutationRequest>

export const CreateRecipeMutationResponse = CreateRecipe200

export type CreateRecipeMutationResponse = z.infer<typeof CreateRecipeMutationResponse>