/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

import { AdminRecipeDto } from './AdminRecipeDto'
import { RecipeRequest } from './RecipeRequest'

/**
 * @description OK
 */
export const CreateRecipe200 = AdminRecipeDto

export type CreateRecipe200 = z.infer<typeof CreateRecipe200>

export const CreateRecipeMutationRequest = RecipeRequest

export type CreateRecipeMutationRequest = z.infer<typeof CreateRecipeMutationRequest>

export const CreateRecipeMutationResponse = CreateRecipe200

export type CreateRecipeMutationResponse = z.infer<typeof CreateRecipeMutationResponse>