/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const DeleteFeedbackPathParams = z.object({
  feedbackId: z.coerce.number().int(),
})

export type DeleteFeedbackPathParams = z.infer<typeof DeleteFeedbackPathParams>

export const DeleteFeedbackQueryParams = z
  .object({
    slowdown: z.coerce.number().int().optional(),
  })
  .optional()

export type DeleteFeedbackQueryParams = z.infer<typeof DeleteFeedbackQueryParams>

/**
 * @description OK
 */
export const DeleteFeedback200 = z.unknown()

export type DeleteFeedback200 = z.infer<typeof DeleteFeedback200>

export const DeleteFeedbackMutationResponse = DeleteFeedback200

export type DeleteFeedbackMutationResponse = z.infer<typeof DeleteFeedbackMutationResponse>