/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { AdminRecipeDto } from './AdminRecipeDto'
import { z } from 'zod/v4'

export const GetAdminRecipePathParams = z.object({
  recipeId: z.coerce.number().int(),
})

export type GetAdminRecipePathParams = z.infer<typeof GetAdminRecipePathParams>

export const GetAdminRecipeQueryParams = z
  .object({
    slowdown: z.coerce.number().int().optional(),
  })
  .optional()

export type GetAdminRecipeQueryParams = z.infer<typeof GetAdminRecipeQueryParams>

/**
 * @description OK
 */
export const GetAdminRecipe200 = AdminRecipeDto

export type GetAdminRecipe200 = z.infer<typeof GetAdminRecipe200>

export const GetAdminRecipeQueryResponse = GetAdminRecipe200

export type GetAdminRecipeQueryResponse = z.infer<typeof GetAdminRecipeQueryResponse>