/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

import { CategoryDto } from './CategoryDto'

/**
 * @description OK
 */
export const GetCategories200 = z.array(CategoryDto)

export type GetCategories200 = z.infer<typeof GetCategories200>

export const GetCategoriesQueryResponse = GetCategories200

export type GetCategoriesQueryResponse = z.infer<typeof GetCategoriesQueryResponse>