/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

import { ImageDto } from './ImageDto'

export const GetImageByIdPathParams = z.object({
  imageId: z.string(),
})

export type GetImageByIdPathParams = z.infer<typeof GetImageByIdPathParams>

export const GetImageByIdQueryParams = z
  .object({
    slowdown: z.coerce.number().int().optional(),
  })
  .optional()

export type GetImageByIdQueryParams = z.infer<typeof GetImageByIdQueryParams>

/**
 * @description OK
 */
export const GetImageById200 = ImageDto

export type GetImageById200 = z.infer<typeof GetImageById200>

export const GetImageByIdQueryResponse = GetImageById200

export type GetImageByIdQueryResponse = z.infer<typeof GetImageByIdQueryResponse>