/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

import { ImageDto } from './ImageDto'

/**
 * @description OK
 */
export const GetImages200 = z.array(ImageDto)

export type GetImages200 = z.infer<typeof GetImages200>

export const GetImagesQueryResponse = GetImages200

export type GetImagesQueryResponse = z.infer<typeof GetImagesQueryResponse>