/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { MealTypeDto } from './MealTypeDto'
import { z } from 'zod/v4'

export const GetMealTypesQueryParams = z
  .object({
    slowdown: z.coerce.number().int().optional(),
  })
  .optional()

export type GetMealTypesQueryParams = z.infer<typeof GetMealTypesQueryParams>

/**
 * @description OK
 */
export const GetMealTypes200 = z.array(MealTypeDto)

export type GetMealTypes200 = z.infer<typeof GetMealTypes200>

export const GetMealTypesQueryResponse = GetMealTypes200

export type GetMealTypesQueryResponse = z.infer<typeof GetMealTypesQueryResponse>