/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

import { MealTypeDto } from './MealTypeDto'

/**
 * @description OK
 */
export const GetMealTypes200 = z.array(MealTypeDto)

export type GetMealTypes200 = z.infer<typeof GetMealTypes200>

export const GetMealTypesQueryResponse = GetMealTypes200

export type GetMealTypesQueryResponse = z.infer<typeof GetMealTypesQueryResponse>