/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

import { MeDto } from './MeDto'

export const GetMeQueryParams = z
  .object({
    slowdown: z.coerce.number().int().optional(),
  })
  .optional()

export type GetMeQueryParams = z.infer<typeof GetMeQueryParams>

/**
 * @description OK
 */
export const GetMe200 = MeDto

export type GetMe200 = z.infer<typeof GetMe200>

export const GetMeQueryResponse = GetMe200

export type GetMeQueryResponse = z.infer<typeof GetMeQueryResponse>