/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { PageResponseAdminRecipeDto } from './PageResponseAdminRecipeDto'
import { z } from 'zod/v4'

export const GetRecipeDashboardListQueryParams = z
  .object({
    page: z.coerce.number().int().optional(),
    size: z.coerce.number().int().optional(),
    slowdown: z.coerce.number().int().optional(),
  })
  .optional()

export type GetRecipeDashboardListQueryParams = z.infer<typeof GetRecipeDashboardListQueryParams>

/**
 * @description OK
 */
export const GetRecipeDashboardList200 = PageResponseAdminRecipeDto

export type GetRecipeDashboardList200 = z.infer<typeof GetRecipeDashboardList200>

export const GetRecipeDashboardListQueryResponse = GetRecipeDashboardList200

export type GetRecipeDashboardListQueryResponse = z.infer<typeof GetRecipeDashboardListQueryResponse>