/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const IngredientRequest = z.object({
  amount: z.number(),
  name: z.string(),
  unit: z.string(),
})

export type IngredientRequest = z.infer<typeof IngredientRequest>