/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const InstructionRequest = z.object({
  description: z.string(),
})

export type InstructionRequest = z.infer<typeof InstructionRequest>