/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const InstructionDto = z.object({
  description: z.string(),
})

export type InstructionDto = z.infer<typeof InstructionDto>