/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const LoginRequest = z.object({
  password: z.string(),
  username: z.string(),
})

export type LoginRequest = z.infer<typeof LoginRequest>