/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const MealTypeDto = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
})

export type MealTypeDto = z.infer<typeof MealTypeDto>