/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const MeDto = z.object({
  fullname: z.string(),
})

export type MeDto = z.infer<typeof MeDto>