/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const NewApprovalStatus = z.enum(['APPROVED', 'REJECTED'])

export type NewApprovalStatus = z.infer<typeof NewApprovalStatus>