/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { CreateRecipeMutationRequest, CreateRecipe200, CreateRecipeMutationResponse, CreateRecipeQueryParams } from './CreateRecipe'
import { DeleteFeedback200, DeleteFeedbackMutationResponse, DeleteFeedbackPathParams, DeleteFeedbackQueryParams } from './DeleteFeedback'
import { GetAdminRecipe200, GetAdminRecipeQueryResponse, GetAdminRecipePathParams, GetAdminRecipeQueryParams } from './GetAdminRecipe'
import { GetAllImages200, GetAllImagesQueryResponse, GetAllImagesQueryParams } from './GetAllImages'
import { GetCategories200, GetCategoriesQueryResponse, GetCategoriesQueryParams } from './GetCategories'
import { GetFeedbackDashboardList200, GetFeedbackDashboardListQueryResponse, GetFeedbackDashboardListQueryParams } from './GetFeedbackDashboardList'
import { GetImageById200, GetImageByIdQueryResponse, GetImageByIdPathParams, GetImageByIdQueryParams } from './GetImageById'
import { GetMe200, GetMeQueryResponse, GetMeQueryParams } from './GetMe'
import { GetMealTypes200, GetMealTypesQueryResponse, GetMealTypesQueryParams } from './GetMealTypes'
import { GetRecipeDashboardList200, GetRecipeDashboardListQueryResponse, GetRecipeDashboardListQueryParams } from './GetRecipeDashboardList'
import {
  SetFeedbackApprovalStatusMutationRequest,
  SetFeedbackApprovalStatus200,
  SetFeedbackApprovalStatusMutationResponse,
  SetFeedbackApprovalStatusPathParams,
  SetFeedbackApprovalStatusQueryParams,
} from './SetFeedbackApprovalStatus'
import { UpdateRecipeMutationRequest, UpdateRecipe200, UpdateRecipeMutationResponse, UpdateRecipePathParams, UpdateRecipeQueryParams } from './UpdateRecipe'
import { UploadImageMutationRequest, UploadImage200, UploadImageMutationResponse } from './UploadImage'

export const operations = {
  getCategories: {
    request: undefined,
    parameters: {
      path: undefined,
      query: GetCategoriesQueryParams,
      header: undefined,
    },
    responses: {
      200: GetCategories200,
      default: GetCategoriesQueryResponse,
    },
    errors: {},
  },
  getFeedbackDashboardList: {
    request: undefined,
    parameters: {
      path: undefined,
      query: GetFeedbackDashboardListQueryParams,
      header: undefined,
    },
    responses: {
      200: GetFeedbackDashboardList200,
      default: GetFeedbackDashboardListQueryResponse,
    },
    errors: {},
  },
  deleteFeedback: {
    request: undefined,
    parameters: {
      path: DeleteFeedbackPathParams,
      query: DeleteFeedbackQueryParams,
      header: undefined,
    },
    responses: {
      200: DeleteFeedback200,
      default: DeleteFeedbackMutationResponse,
    },
    errors: {},
  },
  setFeedbackApprovalStatus: {
    request: SetFeedbackApprovalStatusMutationRequest,
    parameters: {
      path: SetFeedbackApprovalStatusPathParams,
      query: SetFeedbackApprovalStatusQueryParams,
      header: undefined,
    },
    responses: {
      200: SetFeedbackApprovalStatus200,
      default: SetFeedbackApprovalStatusMutationResponse,
    },
    errors: {},
  },
  getAllImages: {
    request: undefined,
    parameters: {
      path: undefined,
      query: GetAllImagesQueryParams,
      header: undefined,
    },
    responses: {
      200: GetAllImages200,
      default: GetAllImagesQueryResponse,
    },
    errors: {},
  },
  uploadImage: {
    request: UploadImageMutationRequest,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: UploadImage200,
      default: UploadImageMutationResponse,
    },
    errors: {},
  },
  getImageById: {
    request: undefined,
    parameters: {
      path: GetImageByIdPathParams,
      query: GetImageByIdQueryParams,
      header: undefined,
    },
    responses: {
      200: GetImageById200,
      default: GetImageByIdQueryResponse,
    },
    errors: {},
  },
  getMe: {
    request: undefined,
    parameters: {
      path: undefined,
      query: GetMeQueryParams,
      header: undefined,
    },
    responses: {
      200: GetMe200,
      default: GetMeQueryResponse,
    },
    errors: {},
  },
  getMealTypes: {
    request: undefined,
    parameters: {
      path: undefined,
      query: GetMealTypesQueryParams,
      header: undefined,
    },
    responses: {
      200: GetMealTypes200,
      default: GetMealTypesQueryResponse,
    },
    errors: {},
  },
  getRecipeDashboardList: {
    request: undefined,
    parameters: {
      path: undefined,
      query: GetRecipeDashboardListQueryParams,
      header: undefined,
    },
    responses: {
      200: GetRecipeDashboardList200,
      default: GetRecipeDashboardListQueryResponse,
    },
    errors: {},
  },
  createRecipe: {
    request: CreateRecipeMutationRequest,
    parameters: {
      path: undefined,
      query: CreateRecipeQueryParams,
      header: undefined,
    },
    responses: {
      200: CreateRecipe200,
      default: CreateRecipeMutationResponse,
    },
    errors: {},
  },
  getAdminRecipe: {
    request: undefined,
    parameters: {
      path: GetAdminRecipePathParams,
      query: GetAdminRecipeQueryParams,
      header: undefined,
    },
    responses: {
      200: GetAdminRecipe200,
      default: GetAdminRecipeQueryResponse,
    },
    errors: {},
  },
  updateRecipe: {
    request: UpdateRecipeMutationRequest,
    parameters: {
      path: UpdateRecipePathParams,
      query: UpdateRecipeQueryParams,
      header: undefined,
    },
    responses: {
      200: UpdateRecipe200,
      default: UpdateRecipeMutationResponse,
    },
    errors: {},
  },
} as const

export const paths = {
  '/api/admin/categories': {
    get: operations['getCategories'],
  },
  '/api/admin/feedback-dashboard-list': {
    get: operations['getFeedbackDashboardList'],
  },
  '/api/admin/feedback/{feedbackId}': {
    delete: operations['deleteFeedback'],
  },
  '/api/admin/feedback/{feedbackId}/approval-status': {
    patch: operations['setFeedbackApprovalStatus'],
  },
  '/api/admin/images': {
    get: operations['getAllImages'],
    post: operations['uploadImage'],
  },
  '/api/admin/images/{imageId}': {
    get: operations['getImageById'],
  },
  '/api/admin/me': {
    get: operations['getMe'],
  },
  '/api/admin/meal-types': {
    get: operations['getMealTypes'],
  },
  '/api/admin/recipe-dashboard-list': {
    get: operations['getRecipeDashboardList'],
  },
  '/api/admin/recipes': {
    post: operations['createRecipe'],
  },
  '/api/admin/recipes/{recipeId}': {
    get: operations['getAdminRecipe'],
    put: operations['updateRecipe'],
  },
} as const