/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { AdminRecipeDto } from './AdminRecipeDto'
import { z } from 'zod/v4'

export const PageResponseAdminRecipeDto = z.object({
  get content() {
    return z.array(AdminRecipeDto)
  },
  hasNext: z.boolean(),
  hasPrevious: z.boolean(),
  meta: z.string().optional(),
  pageNumber: z.int(),
  totalPages: z.int(),
})

export type PageResponseAdminRecipeDto = z.infer<typeof PageResponseAdminRecipeDto>