/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { NewApprovalStatus } from './NewApprovalStatus'
import { z } from 'zod/v4'

export const SetFeedbackApprovalStatusRequest = z.object({
  get newApprovalStatus() {
    return NewApprovalStatus
  },
})

export type SetFeedbackApprovalStatusRequest = z.infer<typeof SetFeedbackApprovalStatusRequest>