/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { AdminRecipeDto } from './AdminRecipeDto'
import { RecipeRequest } from './RecipeRequest'
import { z } from 'zod/v4'

export const UpdateRecipePathParams = z.object({
  recipeId: z.string(),
})

export type UpdateRecipePathParams = z.infer<typeof UpdateRecipePathParams>

export const UpdateRecipeQueryParams = z
  .object({
    slowdown: z.coerce.number().int().optional(),
  })
  .optional()

export type UpdateRecipeQueryParams = z.infer<typeof UpdateRecipeQueryParams>

/**
 * @description OK
 */
export const UpdateRecipe200 = AdminRecipeDto

export type UpdateRecipe200 = z.infer<typeof UpdateRecipe200>

export const UpdateRecipeMutationRequest = RecipeRequest

export type UpdateRecipeMutationRequest = z.infer<typeof UpdateRecipeMutationRequest>

export const UpdateRecipeMutationResponse = UpdateRecipe200

export type UpdateRecipeMutationResponse = z.infer<typeof UpdateRecipeMutationResponse>